//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zestork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobData
    {
        public int Id { get; set; }
        public string Category { get; set; }
        public string SubCategory { get; set; }
        public string Data { get; set; }
        public string PostedBy { get; set; }
        public string StartDate { get; set; }
        public string Status { get; set; }
        public string EndDate { get; set; }
    }
}
