//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zestork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkedInAuthApiData
    {
        public int Id { get; set; }
        public string oauth_Token { get; set; }
        public string oauth_TokenSecret { get; set; }
        public string oauth_verifier { get; set; }
    }
}
